# These are supported funding model platforms

custom: #https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=dennis@beerboys.de&lc=DE&item_name=FritzHome%20-%20Donation&item_number=none&custom=website&currency_code=EUR&bn=PP%2dDonationsBF
